FROM node:16

# Add Docker CLI so Jenkins can communicate with Docker.
COPY --from=docker:cli /usr/local/bin/docker /usr/local/bin/docker

# Jenkins Docker Pipeline will run the container with
# the Jenkins user ID when required.
# Do not set USER node here.
